default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0

development: &development
  <<: *default
  database: psymic_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: psymic_test
  username: postgres
  password: postgres
  host: localhost

staging:
  <<: *development

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PWD"] %>